name: Android CI
on:
  push:
    branches: ["ci/cd"]
  pull_request:
    branches: [ "ci/cd" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: setup graddle
        uses: gradle/gradle-build-action@v2
      - name: build app
        run: ./gradlew assemble
