name: Android Testing CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: gradle

      - name: Run Specific Unit Test
        run: ./gradlew testDebugUnitTest --tests "com.delivery.tecnokargo.login.domain.LoginUseCaseTest"

